import {
  Container,
  Yellow,
  Line,
  Purple,
  Blue,
  Green,
  Prop,
  DeepBlue,
} from "../styles/JSON";

const About = () => {
  return (
    <>
      <Container>
        <div>
          <Line>1</Line>&emsp;&emsp;<Yellow>{`{ `}</Yellow>
        </div>
        <div>
          <Line>2</Line>&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>
              <Blue>"</Blue>
            </Blue>
            <Purple>name</Purple>
            <Blue>
              <Blue>"</Blue>:
            </Blue>
          </span>
          <span>
            <Blue> "</Blue>
            <Green>Diptangshu Ghosh</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>3</Line>&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Purple>summary</Purple>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <span>
            <Blue>"</Blue>
            <Green>
              I am a passionate Front-End developer. I love to build responsive
              user-friendly websites that look visually appealing.
            </Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>4</Line>&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Purple>job</Purple>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <span>
            <Blue>"</Blue>
            <Green>Associate Consultant</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>5</Line>&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Purple>organization</Purple>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <span>
            <Blue>"</Blue>
            <Green>PricewaterhouseCoopers India</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>6</Line>&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Purple>location</Purple>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <span>
            <Blue>"</Blue>
            <Green>Kolkata, West Bengal</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>7</Line>&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Purple>skills</Purple>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <Purple>{`{`}</Purple>
        </div>
        <div>
          <Line>8</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Prop>frontend</Prop>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <DeepBlue>[ </DeepBlue>
        </div>
        <div>
          <Line>9</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>JavaScript/ES6</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>10</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>HTML/HTML5</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>11</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>CSS/CSS3</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>12</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>React.js</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>13</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Bootstrap</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>14</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Styled Components</Green>
            <Blue>"</Blue>
          </span>
        </div>
        <div>
          <Line>15</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <DeepBlue>]</DeepBlue>
          <Blue>,</Blue>
        </div>
        <div>
          <Line>16</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Prop>backend</Prop>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <DeepBlue>[ </DeepBlue>
        </div>
        <div>
          <Line>17</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Node.js</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>18</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Express</Green>
            <Blue>"</Blue>
          </span>
        </div>
        <div>
          <Line>19</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <DeepBlue>]</DeepBlue>
          <Blue>,</Blue>
        </div>
        <div>
          <Line>20</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Prop>database</Prop>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <DeepBlue>[ </DeepBlue>
        </div>
        <div>
          <Line>21</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>MongoDB</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>22</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>MS SQL</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>23</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>MySQL</Green>
            <Blue>"</Blue>
          </span>
        </div>
        <div>
          <Line>24</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <DeepBlue>]</DeepBlue>
          <Blue>,</Blue>
        </div>
        <div>
          <Line>25</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Prop>tool</Prop>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <DeepBlue>[ </DeepBlue>
        </div>
        <div>
          <Line>26</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>VS Code</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>27</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Git</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>28</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>GitHub</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>29</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>npm</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>30</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Heroku</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>31</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Alteryx</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>32</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Power Bi</Green>
            <Blue>"</Blue>
          </span>
        </div>
        <div>
          <Line>33</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <DeepBlue>]</DeepBlue>
          <Blue>,</Blue>
        </div>
        <div>
          <Line>34</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Prop>language</Prop>
            <Blue>
              <Blue>"</Blue>:
            </Blue>{" "}
          </span>
          <DeepBlue>[ </DeepBlue>
        </div>
        <div>
          <Line>35</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>English</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>36</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Hindi</Green>
            <Blue>
              <Blue>"</Blue>,
            </Blue>
          </span>
        </div>
        <div>
          <Line>37</Line>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <span>
            <Blue>"</Blue>
            <Green>Bengali</Green>
            <Blue>"</Blue>
          </span>
        </div>
        <div>
          <Line>38</Line>&emsp;&emsp;&emsp;&emsp;&emsp;
          <DeepBlue>]</DeepBlue>
        </div>
        <div>
          <Line>39</Line>&emsp;&emsp;&emsp;
          <Purple>{`}`}</Purple>
        </div>
        <div>
          <Line>40</Line>&emsp;&emsp;
          <Yellow>{`}`}</Yellow>
        </div>
      </Container>
    </>
  );
};

export default About;
